apiVersion: v1
kind: Service
metadata:
  name: sp-rdbms
  labels:
    app: sp-rdbms
    pattern: wso2sp-pattern-distributed
spec:
  ports:
    - port: 3306
  selector:
    app: sp-rdbms
    tier: sp-rdbms
    pattern: wso2sp-pattern-distributed
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sp-rdbms-deployment
  labels:
    app: sp-rdbms
    pattern: wso2sp-pattern-distributed
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sp-rdbms
        tier: sp-rdbms
        pattern: wso2sp-pattern-distributed
    spec:
      containers:
      - image: mysql:5.7
        name: sp-rdbms
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "1Gi"
        #   requests:
        #     memory: "1Gi"
        args: ["--max-connections", "10000"]
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: SP_MGT_DB
          - name: MYSQL_USER
            value: wso2carbon
          - name: MYSQL_PASSWORD
            value: wso2carbon
        ports:
        - containerPort: 3306
          name: sp-rdbms
        volumeMounts:
        - name: mysql-dbscripts
          mountPath: /docker-entrypoint-initdb.d
        - name: sp-rdbms-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-dbscripts
        configMap:
          name: mysql-dbscripts
      - name: sp-rdbms-persistent-storage
        persistentVolumeClaim:
         claimName: sp-rdbms-volume-claim
