apiVersion: v1
kind: Service
metadata:
  name: wso2sp-receiver
  labels:
    node: wso2sp-receiver
    pattern: wso2sp-pattern-distributed
spec:
  ports:
    # ports that this service should serve on
    -
      name: 'http-port-1'
      port: 9090
      protocol: TCP
    -
      name: 'https-port-1'
      port: 9444
      protocol: TCP
    -
      name: 'https-port-2'
      port: 9544
      protocol: TCP

  # label keys and values that must match in order to receive traffic for this service
  selector:
    node: wso2sp-receiver
    pattern: wso2sp-pattern-distributed
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2sp-receiver
  labels:
    app: wso2sp-receiver
    node: wso2sp-receiver
    pattern: wso2sp-pattern-distributed
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: wso2sp-receiver
        node: wso2sp-receiver
        pattern: wso2sp-pattern-distributed
    spec:
      containers:
      -
        image: wso2/wso2sp-worker:4.4.0
        name: wso2sp-receiver
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "2Gi"
        #   requests:
        #     memory: "1Gi"
        command: ['sh', '-c', sleep 20 && /home/wso2carbon/init.sh]
        env:
        -
          name: WSO2_SERVER_PROFILE
          value: "worker"
        -
          name: OFFSET
          value: "1"
        -
          name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        -
          name: RECEIVER_NODE
          value: "true"
        -
          name: NODE_PORT
          value: "9444"

        ports:
        -
          containerPort: 9090
          protocol: "TCP"
        -
          containerPort: 9444
          protocol: "TCP"
        -
          containerPort: 9543
          protocol: "TCP"
        -
          containerPort: 9544
          protocol: "TCP"
        -
          containerPort: 9711
          protocol: "TCP"
        -
          containerPort: 9611
          protocol: "TCP"
        -
          containerPort: 7711
          protocol: "TCP"
        -
          containerPort: 7611
          protocol: "TCP"
        -
          containerPort: 7070
          protocol: "TCP"
        -
          containerPort: 7443
          protocol: "TCP"
        volumeMounts:
        - name: sp-worker-conf
          mountPath: "/home/wso2carbon/wso2-config-volume/conf/worker/"
        - name: sp-worker-bin
          mountPath: "/home/wso2carbon/kubernetes-volumes/worker/bin/"
        livenessProbe:
          tcpSocket:
            port: 9444
          initialDelaySeconds: 70
          periodSeconds: 20
      volumes:
      - name: sp-worker-conf
        configMap:
          name: sp-worker-conf
      - name: sp-worker-bin
        configMap:
          name: sp-worker-bin
