apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sp-rdbms-volume-claim
  labels:
    app: sp-rdbms
    pattern: wso2sp-pattern-distributed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""