apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sp-mgt-volume-claim
  labels:
      app: wso2sp-manager
      pattern: wso2sp-pattern-distributed
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""