
DROP DATABASE IF EXISTS SP_MGT_DB;
DROP DATABASE IF EXISTS SP_WORKER_STATE_DB;

CREATE DATABASE SP_MGT_DB;
CREATE DATABASE SP_WORKER_STATE_DB;

CREATE USER IF NOT EXISTS 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';
GRANT ALL ON SP_MGT_DB.* TO 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';
GRANT ALL ON SP_WORKER_STATE_DB.* TO 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';